version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ../
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - /home/faizii/capitalbeting.com:/var/www/html/
        ports:
            - 80:80


    db:
      image: docker.io/bitnami/redis:7.0
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      ports:
        - '6379:6379'

