version: '3'
services:
    php-apache-environment:
        container_name: main
        image: dexterquazi/capitalbeting.com
        depends_on:
            - db
        volumes:
            - /home/ec2-user/capitalbeting.com/:/var/www/html/
        ports:
            - 80:80
            - 443:443

    db:
      image: docker.io/bitnami/redis:7.0
      ports:
        - '6379:6379'
      depends_on:
        - redis-primary
      environment:
        - REDIS_REPLICATION_MODE=slave
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
