version: '3'
services:
    php-apache-environment:
        container_name: main
        image: dexterquazi/capitalbeting.com
        depends_on:
            - db
        volumes:
            - /home/ec2-user/capitalbeting.com/:/var/www/html/
        ports:
            - 80:80
            - 443:443

    db:
      depends_on:
        - redis-primary
      image: dexterquazi/redis
      ports:
        - '6379:6379'
      environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_password
      - REDIS_PASSWORD=my_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    redis-primary:
      image: docker.io/bitnami/redis:7.0
      ports:
        - '6379'
      environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    
